name: prod-deploy-android.yml

on:
  push:
    tags:
      - 'release/v*'
      - 'release/android/v*'

jobs:
  qa-stage-deploy-android:
    name: playstore deploy android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Install dependencies
        run: yarn install

      - name: Generate Codegen Artifacts
        run: cd android && ./gradlew generateCodegenArtifactsFromSchema

      - name: Install Fastlane
        run: cd android && bundle install && cd ..

      - name: Set Version Code (Android Studio)
        run: |
          cd android && bundle exec fastlane increment_version_code version_code:${{ vars.VERSION_CODE }} && cd ..

      - name: Increment Version Code
        if: ${{ success() }}
        run: |
          echo "NEW_VERSION_CODE=$((VERSION_CODE + 1))" >> $GITHUB_ENV
        env:
          VERSION_CODE: ${{ vars.VERSION_CODE }}

      - name: Decode Google Credentials
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > google-credentials.json

      - name: Execute Fastlane command
        run: cd android && fastlane android_prod_deploy_to_play_store_distribution
        env:
          FASTLANE_SKIP_UPDATE_CHECK: true
          PROD_GOOGLE_APPLICATION_CREDENTIALS: ../google-credentials.json
